/// A small, hand-picked set: the emoji people put in email. [glyph, name, keywords].
/// The most-used come first, so the bare list is useful before anything is typed.
/// Searched by English name and keywords whatever the app language is.
const RAW = [
  ['👍', 'thumbs up', 'like yes approve ok agree'],
  ['🙏', 'folded hands', 'thanks thank you please pray'],
  ['😊', 'smiling face', 'smile blush happy pleased'],
  ['😀', 'grinning face', 'smile happy grin'],
  ['😂', 'tears of joy', 'laugh lol funny joy'],
  ['❤️', 'red heart', 'love heart'],
  ['🎉', 'party popper', 'tada celebrate congratulations party'],
  ['✅', 'check mark', 'done yes tick complete'],
  ['👋', 'waving hand', 'hello hi bye wave'],
  ['🙂', 'slight smile', 'smile fine friendly'],
  ['😉', 'winking face', 'wink joke'],
  ['🤔', 'thinking face', 'hmm think consider'],
  ['👏', 'clapping hands', 'clap applause well done bravo'],
  ['💪', 'flexed biceps', 'strong muscle flex power'],
  ['🔥', 'fire', 'hot lit great'],
  ['✨', 'sparkles', 'shiny new magic'],
  ['🚀', 'rocket', 'launch ship fast go'],
  ['💡', 'light bulb', 'idea insight'],
  ['⭐', 'star', 'favorite favourite rating'],
  ['📎', 'paperclip', 'attachment attach file'],
  ['📅', 'calendar', 'date schedule meeting'],
  ['📞', 'telephone', 'phone call'],
  ['📧', 'e-mail', 'email mail envelope message'],
  ['📝', 'memo', 'note write document'],
  ['⚠️', 'warning', 'caution careful alert'],
  ['❌', 'cross mark', 'no wrong cancel delete'],
  ['❓', 'question mark', 'question ask'],
  ['❗', 'exclamation mark', 'important attention'],
  ['🤝', 'handshake', 'deal agreement partnership'],
  ['🙌', 'raising hands', 'celebrate hooray praise'],
  ['👌', 'ok hand', 'okay perfect fine'],
  ['👎', 'thumbs down', 'dislike no disagree'],
  ['✌️', 'victory hand', 'peace two'],
  ['🤞', 'crossed fingers', 'luck hope'],
  ['🫡', 'saluting face', 'salute respect'],
  ['👀', 'eyes', 'look see watching'],
  ['😃', 'grinning face with big eyes', 'smiley happy'],
  ['😄', 'grinning face with smiling eyes', 'happy laugh grin'],
  ['😁', 'beaming face', 'grin happy'],
  ['😆', 'grinning squinting face', 'laughing haha'],
  ['😅', 'grinning face with sweat', 'relief phew nervous'],
  ['🤣', 'rolling on the floor laughing', 'rofl lol hilarious'],
  ['😇', 'smiling face with halo', 'angel innocent'],
  ['🥰', 'smiling face with hearts', 'love adore'],
  ['😍', 'heart eyes', 'love crush wow'],
  ['😘', 'face blowing a kiss', 'kiss love'],
  ['😋', 'face savoring food', 'yum tasty delicious'],
  ['😎', 'smiling face with sunglasses', 'cool sunglasses'],
  ['🤗', 'hugging face', 'hug thanks warm'],
  ['🥳', 'partying face', 'party celebrate birthday'],
  ['🤯', 'exploding head', 'mind blown shocked'],
  ['😬', 'grimacing face', 'awkward oops'],
  ['😌', 'relieved face', 'relief calm'],
  ['🙄', 'face with rolling eyes', 'eye roll whatever'],
  ['😏', 'smirking face', 'smirk'],
  ['😐', 'neutral face', 'meh straight'],
  ['😕', 'confused face', 'confused unsure'],
  ['😟', 'worried face', 'worry concern'],
  ['😢', 'crying face', 'sad tear'],
  ['😭', 'loudly crying face', 'sob sad cry'],
  ['😤', 'face with steam from nose', 'huff frustrated'],
  ['😡', 'enraged face', 'angry mad'],
  ['😱', 'face screaming in fear', 'scream shocked fear'],
  ['😳', 'flushed face', 'embarrassed blush'],
  ['🥺', 'pleading face', 'please puppy eyes'],
  ['😴', 'sleeping face', 'sleep tired zzz'],
  ['😷', 'face with medical mask', 'sick mask ill'],
  ['🤒', 'face with thermometer', 'fever sick ill'],
  ['🤷', 'person shrugging', 'shrug dunno'],
  ['🤦', 'person facepalming', 'facepalm oops'],
  ['🙋', 'person raising hand', 'question volunteer hand'],
  ['🙈', 'see-no-evil monkey', 'monkey shy oops'],
  ['🫶', 'heart hands', 'love care'],
  ['💙', 'blue heart', 'love blue'],
  ['💚', 'green heart', 'love green'],
  ['🧡', 'orange heart', 'love orange'],
  ['💔', 'broken heart', 'sad heartbreak'],
  ['💯', 'hundred points', 'perfect score 100'],
  ['🌟', 'glowing star', 'shining star'],
  ['🎊', 'confetti ball', 'celebrate party'],
  ['🎁', 'wrapped gift', 'present gift'],
  ['🏆', 'trophy', 'win winner award'],
  ['🥇', 'first place medal', 'gold winner best'],
  ['🎯', 'bullseye', 'target goal aim'],
  ['⏰', 'alarm clock', 'time deadline reminder'],
  ['⏳', 'hourglass', 'waiting time pending'],
  ['🔒', 'locked', 'lock secure private'],
  ['🔑', 'key', 'password access'],
  ['🔗', 'link', 'chain url'],
  ['🔍', 'magnifying glass', 'search find'],
  ['📌', 'pushpin', 'pin important'],
  ['✉️', 'envelope', 'letter mail'],
  ['💼', 'briefcase', 'work business'],
  ['💻', 'laptop', 'computer work'],
  ['📱', 'mobile phone', 'phone cell'],
  ['📈', 'chart increasing', 'growth up graph'],
  ['📉', 'chart decreasing', 'decline down graph'],
  ['💰', 'money bag', 'money cash'],
  ['💸', 'money with wings', 'spend cost expensive'],
  ['🏠', 'house', 'home'],
  ['✈️', 'airplane', 'flight travel trip'],
  ['🚗', 'automobile', 'car drive'],
  ['☕', 'hot beverage', 'coffee tea break'],
  ['🍕', 'pizza', 'food lunch'],
  ['🍺', 'beer mug', 'beer drink'],
  ['🍻', 'clinking beer mugs', 'cheers drinks'],
  ['🥂', 'clinking glasses', 'toast champagne cheers'],
  ['🎂', 'birthday cake', 'birthday cake'],
  ['🌞', 'sun with face', 'sun sunny'],
  ['☀️', 'sun', 'sunny weather'],
  ['🌧️', 'cloud with rain', 'rain weather'],
  ['❄️', 'snowflake', 'snow cold winter'],
  ['🌈', 'rainbow', 'rainbow colours'],
  ['🌍', 'globe', 'earth world international'],
  ['🍀', 'four leaf clover', 'luck lucky'],
  ['🐛', 'bug', 'bug insect defect'],
  ['🤖', 'robot', 'bot ai'],
  ['🧠', 'brain', 'think smart'],
  ['👻', 'ghost', 'ghost boo'],
];

export const EMOJI = RAW.map(([char, name, keywords]) => ({ char, name, keywords }));
