/**
 * Known email open-tracking endpoints.
 *
 * THREE SOURCES, most specific first — the first match names the vendor the
 * dialog shows, so the curated block goes first to keep familiar names on
 * familiar senders (MailTrackerBlocker files Mailchimp's endpoint under
 * "Intuit", which is true and unhelpful).
 *
 *  1. CURATED_PATTERNS   — ours. Senders that post-date both lists below.
 *  2. UGLY_EMAIL_PATTERNS — the public Ugly Email list
 *     (github.com/OneClickLab/ugly-email-trackers, list.txt v4), as shipped by
 *     the MIT-licensed Ugly Email extension. Friendly vendor names.
 *  3. MTB_PATTERNS       — the block list from MailTrackerBlocker
 *     (github.com/apparition47/MailTrackerBlocker, BSD-3-Clause), the macOS
 *     Mail spy-pixel plugin, itself seeded from HEY's list and Simplify Gmail's.
 *     321 vendors / 423 rules and still maintained — this is the long tail.
 *
 * Note on the big-name blocklists: Brave's, DuckDuckGo's and Mozilla's are WEB
 * tracker lists (script and beacon hosts for pages), not email open-tracking
 * endpoints. They overlap only incidentally, which is why the email-specific
 * lists above are the ones bundled here.
 *
 * BUNDLED ON PURPOSE. MailVault does not fetch a blocklist at runtime: an app
 * that phones a server to ask which pixels to block has replaced one tracker
 * with another. Updating this file is a release, like everything else.
 *
 * Each entry is [vendor label, pattern tested against the whole image URL].
 * A hit is a tracker regardless of the image's declared size — utils/
 * trackerDetect.js runs this pass before its shape heuristics for that reason.
 */

/** Ours — senders both upstream lists predate. */
export const CURATED_PATTERNS = [
  ['Klaviyo', /klaviyomail\.com|trk\.klclick\d*\.com/i],
  ['Braze', /\.braze(-images)?\.(com|eu)|appboy\.com/i],
  ['Iterable', /links?\.[a-z0-9-]+\.iterable\.com|iterable\.com\/a\//i],
  ['Customer.io', /customeriomail\.com|track\.customer\.io/i],
  ['Substack', /substack(cdn)?\.com\/open/i],
  ['beehiiv', /beehiiv\.(com|net)\/(o|open)/i],
  ['Brevo', /sendibm\d*\.com|brevo\.com\/track/i],
  ['Omnisend', /omnisend\.com\/(o|open|track)/i],
  ['lemlist', /lemlist\.com\/(o|api\/track)/i],
  ['Woodpecker', /woodpecker\.co\/(o|open)/i],
  ['GMass', /gmass\.co\/(o|open|track)/i],
  ['Amazon SES', /awstrack\.me/i],
  ['Mailchimp', /list-manage\.com\/track\/open|mailchimpapp\.net/i],
  ['MailerLite', /mailerlite\.com\/(o|open)/i],
  ['Zoho Campaigns', /zcsend\.net|campaigns\.zoho\.com\/(o|open)/i],
  ['Meta Pixel', /facebook\.com\/tr\b/i],
  ['Google Analytics', /google-analytics\.com\/(collect|r\/collect)|__utm\.gif/i],
];

/** Upstream: Ugly Email list.txt (v4). */
export const UGLY_EMAIL_PATTERNS = [
  ['MailChimp', /\/track\/open\.php\?u=|list-manage\.com/i],
  ['SendGrid', /\/wf\/open\?upn=/i],
  ['Drip', /dripemail2/i],
  ['Mailgun', /\/e\/o\/([0-9a-zA-Z+\/]{4})*(([0-9a-zA-Z+\/]{2}==)|([0-9a-zA-Z+\/]{3}=))?/i],
  ['Streak', /mailfoogae\.appspot\.com/i],
  ['Bananatag', /bl-1\.com/i],
  ['Yesware', /t\.yesware\.com/i],
  ['Postmark', /pstmrk\.it\/open/i],
  ['Sidekick', /t\.signauxtrois\.com|sidekickopen/i],
  ['TinyLetter', /tinyletterapp\.com/i],
  ['MixMax', /(email|track)\.mixmax\.com|mixmax\.com\/api\/track\/|mixmax\.com\/e\/o|\/\/tracking.*\/api\/track\/v2\//i],
  ['MailTrack', /mltrk\.io\/pixel\/|mailtrack\.io\/trace\/mail\//i],
  ['ToutApp', /toutapp\.com/i],
  ['Litmus', /emltrk\.com/i],
  ['Boomerang', /mailstat\.us\/tr/i],
  ['ContactMonkey', /contactmonkey\.com\/api\/v1\/tracker/i],
  ['Cirrus Insight', /tracking\.cirrusinsight\.com/i],
  ['ConvertKit', /\/\/(.*)\.convertkit-mail([1-9])?\.com\/o\//i],
  ['Polymail', /polymail\.io(\/v2\/z\/)?|share\.polymail\.io/i],
  ['YAMM', /yamm-track\.appspot/i],
  ['GetResponse', /\/open\.html\?x=/i],
  ['phpList', /\/ut\.php\?u=/i],
  ['Close.io', /close\.io\/email_opened|\/\/ml\.closeml\.com\/t\/\w+\/\w+\.png/i],
  ['Constant Contact', /\.net\/on\.jsp\?/i],
  ['Marketo', /\/trk\?t=/i],
  ['Return Path', /returnpath\.net\/pixel\.gif/i],
  ['Outreach', /(outrch|whosen|getoutreach)\.com\/api\/mailings\/opened/i],
  ['Intercom', /\/\/(.*).intercom-\w+.com(\/via)?\//i],
  ['Mailjet', /\/\/links\..*\/oo\/|\.mjt\.lu\/|\/oo\/.*\.gif/i],
  ['Nethunt', /nethunt\.com\/api\/v1\/track\/email\//i],
  ['Superhuman', /r\.superhuman\.com/i],
  ['Apple', /apple\.com\/report\/2\/its_mail_sf/i],
  ['Fast Mail', /list-manage.com\/track\/open\.php/i],
  ['Fresh Mail', /\/o\/\w{10}\/\w{10}\//i],
  ['ActiveCampaign', /\/lt\.php(.*)\?l=open/i],
  ['AWeber', /openrate\.aweber.com/i],
  ['Getnotify', /email81\.com\/case/i],
  ['GrowthDot', /growthdot\.com\/api\/mail-tracking/i],
  ['Hubspot', /t\.hubspotemail\.net|hubspotstarter\.net|t\.(hubspotemail|hubspotfree|signaux|senal|signale|sidekickopen|sigopn|hsmsdd)|t.strk\d{2}\.email|track\.getsidekick\.com|\/e2t\/(o|c|to)\//i],
  ['Mailspring', /getmailspring\.com\/open/i],
  ['Mandrill', /mandrillapp\.com\/track/i],
  ['Mixpanel', /mixpanel\.com\/(trk|track)/i],
  ['SparkPost', /go\.sparkpostmail2\.com\/q\//i],
  ['Salesforce', /\/\/click\..*\/open\.aspx|salesforceiq\.com\/t.png|beacon\.krxd\.net/i],
  ['PersistIQ', /infinite-stream-5194\.herokuapp\.com\/pixel\//i],
  ['Sailthru', /sailthru\.com\/trk/i],
  ['TrackApp', /trackapp\.io\/static\/img\/track\.gif|trackapp\.io\/[a-z]\//i],
  ['Sendinblue', /sendibw{2}\.com\/track\//i],
  ['Segment', /email\.segment\.com\/e\/o\//i],
  ['SalesLoft', /salesloft\.com\/email_trackers|salesloftlinks\.com\/t\//i],
  ['SalesHandy', /saleshandy\.com\/web\/email\/countopened/i],
  ['Shopify', /\/tools\/emails\/open\//i],
  ['Amazon SES', /\/\w*I0\/\w{16}-\w{8}-\w{4}/i],
  ['Cooper Press', /\/open\/\d{3}\/\w{10}/i],
  ['Sare', /\/\/(.*)\.enewsletter\.pl\/(.*)\.gif/i],
  ['Selligent', /\/optiext\/optiextension\.dll\?ID=/i],
  ['Technolutions', /\/\/mx\.technolutions\.net\/ss\/o\/(.*)\/ho\.gif/i],
  ['Vocus', /\/\/tracking\.vocus\.io\//i],
];

/** Upstream: MailTrackerBlocker's getTrackerDict (BSD-3-Clause). */
export const MTB_PATTERNS = [
  ['1&1', /simg.1und1.de/i],
  ['1&1', /oc.ionos.com\/\?utm_rid=/i],
  ['1&1', /t.ionos.com\/oms_p\//i],
  ['365offers.trade', /trk.365offers.trade/i],
  ['3hands', /mi.pbz.jp\//i],
  ['4Cite', /\/\?sv_cid=/i],
  ['ActiveCampaign', /\/lt.php\?/i],
  ['ActiveCampaign', /\/Prod\/link-tracker\?nl=/i],
  ['Act-On', /actonsoftware.com/i],
  ['activecore', /h-cast.jp\/mail_open/i],
  ['Acoustic', /\/open\/log\//i],
  ['ADAC', /mailing.adac.de\/tr\//i],
  ['AdComplete', /\/banman.asp\?/i],
  ['Adtriba', /d.adtriba.com/i],
  ['Adobe', /\/trk\?t=1&mid=/i],
  ['AgileCRM', /agle2.me\/open/i],
  ['Agoda', /xml.agoda.com\/EmailTracking\/api\/emailtracking\/Open/i],
  ['Air Miles', /email.airmiles.ca\/O/i],
  ['Aislelabs', /app.aislelabs.com\/o\/emailv3\/emailv3onepixel.jsp/i],
  ['Alaska Airlines', /click.points-mail.com\/open/i],
  ['Alaska Airlines', /sjv.io\/i\//i],
  ['Alaska Airlines', /gqco.net\/i\//i],
  ['Alibaba', /ae.mmstat.com\/ae.edm.edm_open/i],
  ['Alida', /.png1/i],
  ['All Nippon Airways', /amc.ana.co.jp\/bin\/checker/i],
  ['Amazon', /sellercentral(-europe)?(-japan)?.amazon.+\/nms\/img\//i],
  ['Amazon SES', /.awstrack.me\/I0\//i],
  ['Amazon SES', /aws-track-email-open/i],
  ['Amazon SES', /\/gp\/r.html/i],
  ['Amazon SES', /\/gp\/forum\/email\/tracking/i],
  ['Amazon SES', /amazonappservices.com\/trk/i],
  ['Amazon SES', /amazonappservices.com\/r\//i],
  ['Amazon SES', /awscloud.com\/trk/i],
  ['Amobee', /d.turn.com\/r\//i],
  ['Apo.com', /info.apo.com\/op\//i],
  ['Apple', /apple.com\/report\/2\/its_mail_sf/i],
  ['Apple', /apple_email_link\/spacer/i],
  ['Appriver', /appriver.com\/e1t\/o\//i],
  ['Apptivo', /apptivo.com/i],
  ['Artegic', /elaine-asp.de/i],
  ['Asana', /app.asana.com\/-\/open/i],
  ['Ashby', /app.ashbyhq.com\/api\/beacon\/email-read\//i],
  ['ASUSTeK', /emditpison.asus.com/i],
  ['Atlassian', /i.trellomail.com\/e\/eo/i],
  ['Atlassian', /bitbucket.org\/account\/notifications\/mark-read\//i],
  ['AT&T', /clicks.att.com\/OCT\/eTrac\?EMAIL_ID=/i],
  ['AutoAlert', /dealer.autoalert.com\/email\/tracking\/open/i],
  ['AutoAlert', /fzlnk.com\/AutoAlertEmailHandler.ashx/i],
  ['Aurea', /\/1.gif/i],
  ['AWeber', /openrate.aweber.com/i],
  ['Backpack Internet', /app.bentonow.com\/ahoy\/messages\//i],
  ['Backpack Internet', /track.bentonow.com\/tracking\/emails\//i],
  ['Bananatag', /bl-1.com/i],
  ['Bazaarvoice', /bazaarvoice.com\/a.gif/i],
  ['Bison', /clicks.bisonapp.com/i],
  ['Bandsintown', /px1.bandsintown.com/i],
  ['Benchmark Email', /bmetrack.com\/c\/o/i],
  ['Betrend', /cl.am.md\/\?/i],
  ['Blackbaud', /support.planetary.org\/site\/PixelServer/i],
  ['Blackbaud', /\/smtp.mailopen\?id=/i],
  ['Blueshift.com', /getblueshift.com\/track/i],
  ['British Airways', /britishairways.com\/cms\/global\/assets\/images\/global\/email_images\/structural\/primary1px.gif/i],
  ['Bombcom', /bixel.io/i],
  ['Boomerang', /mailstat.us\/tr/i],
  ['Boots', /boots.com\/rts\/open.aspx/i],
  ['Boxbe', /boxbe.com\/stfopen/i],
  ['Browserstack', /browserstack.com\/images\/mail\/track-open/i],
  ['BuzzStream', /tx.buzzstream.com/i],
  ['Campaigner', /trk.cp20.com\/open\//i],
  ['Cheetah Digital', /\/rts\/open.aspx\?tp=/i],
  ['ChurnZero', /t.churnzero.net\/ss\/o\//i],
  ['CircleCI', /email.circleci.com\/o\//i],
  ['Cirrus Insight', /tracking.cirrusinsight.com/i],
  ['Clarivate', /\/email\/track\?a=/i],
  ['CLICKBOTPROTECTION', /inthemoon.com\/r2.php/i],
  ['ClickMeter', /pixel.watch\//i],
  ['Clio', /app.clio.com\/tracking_pixel/i],
  ['Close', /close.io\/email_opened/i],
  ['Close', /close.com\/email_opened/i],
  ['Close', /dripemail2/i],
  ['cloudHQ', /cloudhq.io\/mail_track/i],
  ['Coda', /coda.io\/logging\/ping/i],
  ['CommissionSoup', /cstrk.net\/imp.aspx\?l=/i],
  ['ConneQuityMailer', /connequitymailer.com\/open\//i],
  ['Conrad', /aktuell.conrad.de\/g.html/i],
  ['Constant Contact', /rs6.net\/on.jsp/i],
  ['ContactMonkey', /contactmonkey.com\/api\/v1\/tracker/i],
  ['ConvertKit', /convertkit-mail.com\/o\//i],
  ['ConvertKit', /open.convertkit-mail2.com\//i],
  ['Copper', /prosperworks.com\/tp\/t/i],
  ['Cprpt', /\/o.aspx\?t=/i],
  ['Creditmantri.com', /mailer.creditmantri.com\/t\//i],
  ['Critical Impact', /portal.criticalimpact.com\/c2\//i],
  ['Cuenote', /cuenote.jp\/c\//i],
  ['Curumeru', /crmf.jp/i],
  ['Customer.io', /customeriomail.com\/e\/o/i],
  ['Customer.io', /track.customer.io\/e\/o/i],
  ['Customer.io', /\/e\/o\/.+/i],
  ['CustomerRings', /c-rings.net\/Mail\/Gif\//i],
  ['Cyberimpact', /app.cyberimpact.com\/footer-image/i],
  ['Data Axle', /ympxl.com\/log.gif/i],
  ['dataX', /openedlog.bdash-cloud.com\/opened/i],
  ['dataX', /openedlog.smart-bdash.com\/opened/i],
  ['Dating Profits', /click.xnxxinc.com\/campaign\/track-email\//i],
  ['Deployteq', /click.centraalbeheer.nl/i],
  ['Deployteq', /e.wehkamp.nl/i],
  ['Deployteq', /e.bax-shop.nl/i],
  ['DidTheyReadIt', /xpostmail.com/i],
  ['Discord', /discord.com\/api\/science\//i],
  ['DocuMatix', /enews.itcu.org\/op\?m=/i],
  ['Doorkeeper', /r.doorkeeper.jp\/.+.png/i],
  ['DotDigital', /trackedlink.net/i],
  ['DotDigital', /dmtrk.net/i],
  ['DotDigital', /email.syntricate.com.au/i],
  ['Driftem', /driftem.com\/ltrack/i],
  ['Drop', /pixel.massdrop.com\/open\/pixel.gif/i],
  ['Dropbox', /dropbox.com\/l\//i],
  ['Dyson', /tracking.dyson.com\/t\//i],
  ['eBay', /ebayadservices.com\/marketingtracking\/v1\/impression/i],
  ['Ebsta', /console.ebsta.com/i],
  ['Ebsta', /ebsta.gif/i],
  ['Ebsta', /ebsta.com\/r\//i],
  ['EdgeSuite', /epidm.edgesuite.net/i],
  ['eGain', /notify.egain.cloud\/egain\/notify\//i],
  ['Email on Acid', /eoapxl.com/i],
  ['EmailTracker.website', /my-email-signature.link/i],
  ['Emarsys', /\/mo\/.+.gif/i],
  ['Emarsys', /emarsys.com\/e2t\/o\//i],
  ['EmberPoint', /rec.mpse.jp/i],
  ['EmberPoint', /\/open.html\?cnid=/i],
  ['Envoke', /envoke.com\/o\//i],
  ['Epic Games', /accts.epicgames.com\/O\//i],
  ['Epsilon', /login.dotomi.com\/ucm\/UCMController/i],
  ['Escalent', /email-analytics.morpace.com/i],
  ['eSputnik', /esputnik.com\/repository\/applications\/commons\/hidden.png/i],
  ['Etransmail', /ftrans03.com\/linktrack\//i],
  ['EventBrite', /eventbrite.com\/emails\/action/i],
  ['EventsInYourArea', /eventsinyourarea.com\/track\//i],
  ['EveryAction', /click.everyaction.com\/j\//i],
  ['Evite', /pippio.com\/api\/sync/i],
  ['Evite', /nli.evite.com\/imp/i],
  ['ezyVet', /ezyvet.com\/email_open_log.php/i],
  ['Fastic', /\/e\/eo\?_t=/i],
  ['Flatastic', /api.flatastic-app.com\/index.php\/img/i],
  ['Flipkart', /flipkart.com\/t\/open/i],
  ['ForMirror', /formirror.com\/open\//i],
  ['FreeLancer', /freelancer.com\/1px.gif/i],
  ['FreshMail', /mail..+.pl\/o\//i],
  ['FreshMail', /\/o\/(w){10,}\/(w){10,}/i],
  ['FrontApp', /app.frontapp.com/i],
  ['FrontApp', /web.frontapp.com\/api/i],
  ['GearBest', /appinthestore.com\/marketing\/mail-user-deal\/open/i],
  ['Gem', /zen.sr\/o/i],
  ['GetBase', /getbase.com\/e1t\/o\//i],
  ['GetNotify', /email81.com\/case/i],
  ['GetResponse', /\/open.html\?x=/i],
  ['GitHub', /github.com\/notifications\/beacon\//i],
  ['Gmass', /ec2-52-26-194-35.us-west-2.compute.amazonaws.com/i],
  ['Gmelius', /gml.email/i],
  ['GoDaddy', /email.cloud.secureclick.net\/view\?/i],
  ['gogcli', /gog-email-tracker-/i],
  ['Google', /ad.doubleclick.net\/ddm\/ad/i],
  ['Google', /google-analytics.com\/collect/i],
  ['Google', /google.com\/appserve\/mkt\/img\//i],
  ['Google', /notifications.google.com\/g\/img\//i],
  ['Google', /youtube.com\/gen_204/i],
  ['Google', /notifications.googleapis.com\/email\/t/i],
  ['Google', /youtube.com\/attribution_link/i],
  ['Grammarly', /grammarly.com\/open/i],
  ['GreenMail', /greenmail.co.in/i],
  ['Groupon', /groupon.com\/analytic\/track.gif\?/i],
  ['GrowthDot', /growthdot.com\/api\/mail-tracking/i],
  ['Hiretual', /api.hiretual.com\/webhooks\/tracking\/open\//i],
  ['Homeaway', /trk.homeaway.com/i],
  ['HubSpot', /t.hubspotemail/i],
  ['HubSpot', /t.hubspotfree/i],
  ['HubSpot', /t.signaux/i],
  ['HubSpot', /t.senal/i],
  ['HubSpot', /t.signale/i],
  ['HubSpot', /t.sidekickopen/i],
  ['HubSpot', /t.sigopn/i],
  ['HubSpot', /t.hsmsdd/i],
  ['Hunter.io', /mltrk.io\/pixel/i],
  ['Hyper Hyper', /hyperhub.com.au\/newhub\/api\/email\/track/i],
  ['iContact', /click.icptrack.com\/icp/i],
  ['Indeed', /subscriptions.indeed.com\/imgping/i],
  ['Inflection', /tracking.inflection.io/i],
  ['Infobip', /\/tracking\/1\/open\//i],
  ['Infusion Software', /infusionsoft.com\/app\/emailOpened/i],
  ['Integral Ad Science', /pixel.adsafeprotected.com/i],
  ['Intercom', /via.intercom.io\/o/i],
  ['Intuit', /list-manage.com\/track\/open.php/i],
  ['Inxmail', /\/d\/d.gif\?/i],
  ['Is-tracking-pixel-api-prod.appspot.com', /is-tracking-pixel-api-prod.appspot.com/i],
  ['Japan Railway', /expy.jp\/c\//i],
  ['Jeeng', /\/stripe\/image\?cs_/i],
  ['LaunchBit', /launchbit.com\/taz-pixel/i],
  ['Lidl', /servicemails.lidl.de\/d\/d.gif/i],
  ['LinkedIn', /linkedin.com\/emimp\//i],
  ['LinkedIn', /help.linkedin.com\/rd\//i],
  ['Litmus', /emltrk.com/i],
  ['Liveclicker', /em.realtime.email\/service\/rte\?kind=duration/i],
  ['LogDNA', /ping.answerbook.com/i],
  ['Keychron', /keychron.com\/_t\/open\//i],
  ['Klaviyo', /trk.klaviyomail.com/i],
  ['Magento', /magento.com\/trk/i],
  ['Magento', /go.rjmetrics.com/i],
  ['Mailbird', /tracking.getmailbird.com\/OpenTrackingPixel\//i],
  ['Mailbutler', /bowtie.mailbutler.io\/tracking\/hit\//i],
  ['Mailcastr', /mailcastr.com\/image\//i],
  ['MailCoral', /mailcoral.com\/open/i],
  ['MailerLite', /\/link\/o\//i],
  ['MailerLite', /clicks.mlsend.com/i],
  ['Mailgun', /\/o\/eJ/i],
  ['MailInifinity', /mailinifinity.com\/ptrack/i],
  ['Mailshake', /w1.mslai.net\/prod\/open\//i],
  ['Mailshake', /w1.msstnu.com\/prod\/open\//i],
  ['Mailspring', /getmailspring.com\/open/i],
  ['Mailspring', /img.secureserver.net\/bbimage.aspx/i],
  ['MailTag', /mailtag.io\/email-event/i],
  ['MailTrack', /mailtrack.io\/trace/i],
  ['MailTrack', /mltrk.io\/pixel/i],
  ['Mailzter', /mailzter.in\/ltrack/i],
  ['Mapp', /\/tr\/p.gif\?/i],
  ['Mapp', /enews.zdnet.com\/imagelibrary\//i],
  ['MDirector', /track.mdrctr.com\/track\/open\/key\//i],
  ['Mercari', /bmo.mercari.jp/i],
  ['MessageGears', /\/o\/4\/eyJhaSI6/i],
  ['Meta', /facebook.com\/aymt\/aa\//i],
  ['Meta', /facebook.com\/r\/v\//i],
  ['Meta', /facebook.com\/email_open_log_pic.php/i],
  ['Meta', /facebookdevelopers.com\/trk/i],
  ['Meta', /fb.com\/trk/i],
  ['MetaData', /metadata.io\/e1t\/o\//i],
  ['Microsoft', /svc.dynamics.com\/t\/i\//i],
  ['Microsoft', /mucp.api.account.microsoft.com/i],
  ['Microsoft', /gridinbound.blob.core.windows.net/i],
  ['Microsoft', /dist.nam.formspro.microsoft.com\/api\/invite\/outbound\//i],
  ['MixMax', /email.mixmax.com/i],
  ['MixMax', /track.mixmax.com/i],
  ['MixMax', /mixmax.com\/api\/track\//i],
  ['Mixpanel', /api.mixpanel.com\/tr/i],
  ['Moneyforward', /tm.moneyforward.com\/I\//i],
  ['Movable Ink', /\/p\/rp\/\w{16}.png/i],
  ['MyEmma', /e2ma.net\/track/i],
  ['MyEmma', /t.e2ma.net/i],
  ['Nation Builder', /nationbuilder.com\/r\/o/i],
  ['NeteCart', /netecart.com\/ltrack/i],
  ['Netflix', /beaconimages.netflix.net\/img\//i],
  ['NetHunt', /nethunt.com\/api\/v1\/track\/email\//i],
  ['NetHunt', /nethunt.co(.*)\?\/pixel.gif/i],
  ['Newegg', /newegg.com\/mr\/.+.gif/i],
  ['NewtonHQ', /tr.cloudmagic.com/i],
  ['NTT', /club-ntt-west.com\/cn-w\/cmn\/img\/1.png/i],
  ['Omnisend', /\/transactional\/track\/.+\?signature=/i],
  ['OpenBracket', /openbracket.co\/track/i],
  ['OpenWork', /openwork.jp\/log_mail_open_com/i],
  ['Opicle', /track.opicle.com/i],
  ['Oracle', /tags.bluekai.com\/site/i],
  ['Oracle', /en25.com\/e\//i],
  ['Oracle', /dynect.net\/trk.php/i],
  ['Oracle', /lifelock.custhelp.com\/rd\//i],
  ['Oracle', /bm5150.com\/t\//i],
  ['Oracle', /bm23.com\/t\//i],
  ['Oracle', /\/t\/o\?/i],
  ['Oracle', /\/pub\/as\?_ri_=/i],
  ['Oracle', /\/e\/FooterImages\/FooterImage/i],
  ['OutMaster', /outmaster.co\/mailer\/index.php\/campaigns\//i],
  ['Outreach', /app.outreach.io/i],
  ['Outreach', /outrch.com\/api\/mailings\/opened/i],
  ['Outreach', /getoutreach.com\/api\/mailings\/opened/i],
  ['Outreach', /a.science-recruiting.com\/api\/mailings\/opened/i],
  ['pafin', /mail.cryptact.com\/ty\/v\//i],
  ['PayBack', /email.payback.in\/a\//i],
  ['PayBack', /mail.payback.in\/tr\//i],
  ['PayPal', /paypal-communication.com\/O\//i],
  ['PayPal', /t.paypal.com\/ts\?/i],
  ['Paystone', /link.datacandy.com\/i\//i],
  ['Paytm', /trk.paytmemail.com/i],
  ['Peach Aviation', /mlapp.flypeach.com\/mail\/prod\/receipt\/read.php\?id=/i],
  ['Peach Aviation', /mag.flypeach.com\/c\//i],
  ['PersistIQ', /infinite-stream-5194.herokuapp.com\/pixel/i],
  ['phpList', /\/ut.php\?u=/i],
  ['PipeDrive', /api.nylas.com\/open/i],
  ['Playdom', /playdom.com\/g/i],
  ['Plusgrade', /upgrade.plusgrade.com\/offer\//i],
  ['Polymail', /polymail.io\/v2\/z\//i],
  ['Polymail', /share.polymail.io/i],
  ['Postmark', /pstmrk.it/i],
  ['Press Ganey', /email.patients.pgsurveying.com/i],
  ['ProlificMail', /prolificmail.com\/ltrack/i],
  ['Qualtrics', /\/WRQualtricsContacts\/Watermark.php/i],
  ['Quora', /quora.com\/qemail\/mark_read/i],
  ['Rabobank', /mail.rabobank.nl\/public\/o\//i],
  ['Rakuten', /img.travel.rakuten.co.jp\/share\/mail\/img\/open\//i],
  ['Rakuten', /r.rakuten.co.jp/i],
  ['Rakuten', /cl.rakuten-bank.co.jp\/rw\/beacon_/i],
  ['Rakuten', /cmb.rakuten-sec.co.jp\/bin\/checker/i],
  ['ReachMail', /\/open\/.+\/image.gif/i],
  ['ReplyCal', /replycal.com\/home\/index\/\?token/i],
  ['ReplyMsg', /replymsg.com/i],
  ['Responder.co.il', /opens.responder.co.il/i],
  ['Rewe', /epost.rewe.de\/action\/view\//i],
  ['Rocketbolt', /email.rocketbolt.com\/o\//i],
  ['Rule', /app.rule.io\/track\/image/i],
  ['Sailthru', /sailthru.com\/trk/i],
  ['Salesforce', /salesforceiq.com\/t.png/i],
  ['Salesforce', /beacon.krxd.net/i],
  ['Salesforce', /app.relateiq.com\/t.png/i],
  ['Salesforce', /nova.collect.igodigital.com/i],
  ['Salesforce', /exct.net\/open.aspx/i],
  ['Salesforce', /\/open.aspx\?/i],
  ['Salesforce', /pixel.inbox.exacttarget.com\/pixel.gif/i],
  ['Salesforce', /welcome.michaelcassel.com\/r\/.+\/open\/1/i],
  ['Salesforce', /pardot.com\/r\//i],
  ['SalesHandy', /saleshandy.com\/web\/email\/countopened/i],
  ['SalesLoft', /salesloft.com\/email_trackers/i],
  ['Selligent', /\/optiext\/optiextension.dll/i],
  ['Selligent', /strongview.com\/t/i],
  ['Selligent', /emsecure.net/i],
  ['Selligent', /selligent.com/i],
  ['Selligent', /slgnt.eu/i],
  ['Selligent', /slgnt.us/i],
  ['Sendinblue', /sendibtd.com/i],
  ['Sendinblue', /sendibw.com\/track\//i],
  ['Sendinblue', /amxe.net/i],
  ['SendGrid', /ablink.hello.wyze.com\/ss\/o\//i],
  ['SendGrid', /ablink.marketing.li.me/i],
  ['SendGrid', /ablink.rider.li.me/i],
  ['SendGrid', /ablink.mail.free-now.com/i],
  ['SendGrid', /ablink.email.etsy.com/i],
  ['SendGrid', /ablink.comms.trainline.com/i],
  ['SendGrid', /ablink.emails.just-eat.co.uk/i],
  ['SendGrid', /ablink.mail.delosdestinations.com/i],
  ['SendGrid', /ablink.m1.cratejoy.com/i],
  ['SendGrid', /sendgrid.net\/wf\/open/i],
  ['SendGrid', /sendgrid.net\/trk/i],
  ['SendGrid', /sendgrid.net\/mpss\/o/i],
  ['SendGrid', /sendgrid.net\/ss\/o/i],
  ['SendGrid', /sendgrid.com\/wf\/open/i],
  ['SendGrid', /sendgrid.com\/trk/i],
  ['SendGrid', /sendgrid.com\/mpss\/o/i],
  ['SendGrid', /sendgrid.com\/ss\/o/i],
  ['SendGrid', /\/wf\/open\?upn=/i],
  ['SendPulse', /stat-pulse.com/i],
  ['Shopify', /\/tools\/emails\/open\//i],
  ['Signal', /signl.live\/tracker/i],
  ['Smore', /smore.com\/app\/reporting\/pixel\//i],
  ['Snov.io', /\/track\/open\/v2-/i],
  ['SparkPost', /mailer.codepen.io\/q/i],
  ['SparkPost', /sptrack.trello.com\/q\//i],
  ['SparkPost', /track.sp.actionkit.com\/q\//i],
  ['SparkPost', /click.email.active.com\/q\//i],
  ['SparkPost', /x.getclockwise.com\/q\//i],
  ['SparkPost', /t.drop.com\/q\//i],
  ['SparkPost', /sp.trk.homeaway.com\/q\//i],
  ['SparkPost', /click.uber.com\/q\//i],
  ['SparkPost', /opens.zapier.com\/q\//i],
  ['SparkPost', /sparkpost.com\/q\//i],
  ['SparkPost', /go.sparkpostmail.com\/q\//i],
  ['SparkPost', /post.spmailtechno.com\/q\//i],
  ['SparkPost', /sparkpostmail2.com/i],
  ['SparkPost', /\/q\/.+~~\//i],
  ['Splio', /trk-2.net\/ouv/i],
  ['Sprinklr', /tracking-prod.sprinklr.com/i],
  ['Staples', /\/ctt\/mktOpen\?/i],
  ['Steam', /store.steampowered.com\/emi\//i],
  ['Step Coupon', /step-coupon.com\/review_mail_read_status.html/i],
  ['Streak', /mailfoogae.appspot.com/i],
  ['Squarespace', /engage.squarespace-mail.com\/v2\/a.gif/i],
  ['Substack', /substack.com\/o\//i],
  ['Superhuman', /r.superhuman.com/i],
  ['Taguchi', /taguchimail.com\/i\/app/i],
  ['TataDocomoBusiness', /tatadocomobusiness.com\/rts\//i],
  ['Techgig', /tj_mailer_opened_count_all.php/i],
  ['Telstra', /tapi.telstra.com\/presentation\/v1\/notification-mngmt\/delivery-status-tracker/i],
  ['The Atlantic', /data-cdn.theatlantic.com\/email.gif/i],
  ['The Chronicle of Higher Education', /d2uowlhdj52lqx.cloudfront.net\/emailbeacon.png/i],
  ['TheTopInbox', /thetopinbox.com\/track\//i],
  ['Thunderhead', /na5.thunderhead.com/i],
  ['Tinyletter', /tinyletterapp.com/i],
  ['ToutApp', /go.toutapp.com/i],
  ['Tripolis', /\/public\/o\/.+\/t.gif/i],
  ['Trustyou', /analytics.trustyou.com\/surveys\/api\/mailing\/events\/invitation\/opened/i],
  ['Twilio', /api.segment.io\/v1\/pixel\/track/i],
  ['Twitch', /spade.twitch.tv\/track/i],
  ['Twitter', /twitter.com\/scribe\/ibis/i],
  ['Unsplash', /email.unsplash.com\/o\//i],
  ['Upland PostUp', /efeedbacktrk.com/i],
  ['US Bancorp', /post-images.com\/amy\/open.action/i],
  ['User.com', /.user.com\/emails\/open\//i],
  ['Validity', /.returnpath.net\/pixel.gif/i],
  ['Validity', /\/ea\/.+\/\?e=/i],
  ['Varibase', /e.varibase.com\/mail\/MOS/i],
  ['Vcommission', /tracking.vcommission.com/i],
  ['Verizon', /verizon.com\/econtact\/ecrm\/EmailTracking.serv/i],
  ['VinSolutions', /vinlens.com\/email.ashx\?c=/i],
  ['VoIP.ms', /voip.ms\/email.php\?id=/i],
  ['Vtiger', /od2.vtiger.com\/shorturl.php/i],
  ['Walmart', /w-mt.co\/g\/rptrcks\/comm-smart-app\/services\/tracking\/openTracker/i],
  ['We Are Web', /tracking.weareweb.in\/index.php\/campaigns\//i],
  ['Webtrekk', /webtrekk.net/i],
  ['Windscribe', /windscribe.com\/pixel/i],
  ['WildApricot', /wildapricot.com\/o\//i],
  ['WildApricot', /wildapricot.org\/emailtracker/i],
  ['WildApricot', /\/EmailTracker\/EmailTracker.ashx/i],
  ['Wise', /links.transferwise.com\/track\//i],
  ['Wise', /api.transferwise.com/i],
  ['Wish', /wish.com\/email-beacon.png/i],
  ['Wix', /shoutout.wix.com/i],
  ['WordPress', /pixel.wp.com\/t.gif/i],
  ['Yahoo!', /a.analytics.yahoo.com\/p.pl/i],
  ['Yahoo! Japan', /dsb.yahoo.co.jp\/api\/v1\/clear.gif/i],
  ['YAMM', /yamm-track.appspot/i],
  ['Yardi', /\/t\/teo\?ref=/i],
  ['Yesware', /yesware.com\/trk/i],
  ['Yesware', /yesware.com\/t\//i],
  ['Yesware', /t.yesware.com/i],
  ['Zendesk', /futuresimple.com\/api\/v1\/sprite.png/i],
  ['Zeta Global', /e.newsletters.cnn.com\/open\//i],
  ['Zeta Global', /e.email.consumerreports.org\/open\//i],
  ['Zoho', /maillist-manage.com\/clicks\//i],
  ['Zoho', /\/open.gif/i],
];

export const TRACKER_PATTERNS = [
  ...CURATED_PATTERNS,
  ...UGLY_EMAIL_PATTERNS,
  ...MTB_PATTERNS,
];
